CREATE TABLE posts (
    id UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    title NVARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    is_public BIT DEFAULT 1,
    user_id UNIQUEIDENTIFIER NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
GO